name: deploy_wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      v-version: ${{ steps.version.outputs.v-version }}
    steps:
      # Can be major, minor, or patch, Update secret variable INCREMENT_TYPE in GitHub Actions Settings
      - name: Set increment type from environment variable
        run: |
          if [ -z "${{ secrets.INCREMENT_TYPE }}" ]; then
            echo "increment=major" >> $GITHUB_ENV
          else
            echo "increment=${{ secrets.INCREMENT_TYPE }}" >> $GITHUB_ENV
          fi
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          release_branch: main
          use_api: true
          increment: ${{ env.increment }}

  build:
    runs-on: ubuntu-latest
    needs: [create_release]
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Create wheel file
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel build setuptools_scm
        PRETEND_VERSION=${{ needs.create_release.outputs.v-version }} python3 -m build --wheel .

    - name: Store the IoT Core Python wheel
      uses: actions/upload-artifact@v4
      with:
        name: iot-core
        path: dist/*.whl
        if-no-files-found: error

  # This is disabled for now
  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: github.repository == 'nyu-mlab/inspector-core-library' && github.ref == 'refs/heads/main'
    needs: [create_release, build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/libinspector  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: write  # Required for creating releases

    steps:
      - name: Download all the wheel file
        uses: actions/download-artifact@v4
        with:
          name: iot-core
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Upload wheel and debian packages to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            dist/*.whl